name: ClearInv
main: com.wwsean08.clear.Clear
<<<<<<< HEAD
version: 1.8.6
=======
version: 1.8.4
>>>>>>> 3233e291748aefed433b8418ebb06bf5162d1b65
commands:
   clear:
      description: This will clear or selectively clear your inventory
      usage: /<command> [item]...
   preview:
      description: This will give you a preview  of another users inventory.
      usage: /<command> <user>
   unpreview:
       description: This will restore your inventory to it's original state
       usage: /<command>
   revert:
       description: This will restore your inventory to it's original state
       usage: /<command>
permissions:
    clear.self:
        description: Allows you to clear stuff from your own inventory
        default: true
    clear.other:
        description: Allows you to clear other players inventory and preview their inventory as well
        default: op
    clear.admin:
        descriptions: Allows you to clear everyones inventory at once
        default: op